{"name": "test_sign_up_negative_17", "status": "broken", "statusDetails": {"message": "ui.utils.exceptions.InvalidRegInfoException: Internal Server Error", "trace": "self = <test_ui.TestUI object at 0x7f21425f4970>\ncreate_fake_user = ('zuevfeofan', '^zSHvb&$Q2', 'ponomarevtaras@rao.com')\nreg_page_object = <ui.pages.reg_page.RegPage object at 0x7f214258fee0>\nhome_page_object = <ui.pages.home_page.HomePage object at 0x7f214258f070>\n\n    @allure.feature('UI tests')\n    @allure.story('Sign up page story')\n    def test_sign_up_negative_17(self, create_fake_user, reg_page_object, home_page_object):\n        \"\"\"Проверка регистрации пользователя при совпадении поля email с уже существующим в БД\"\"\"\n        self.logger.start_logging(\n            f'./project/app_logs/{inspect.getframeinfo(inspect.currentframe()).function}_ui_log.txt')\n        with allure.step('Получаем информацию о пользователях с совпадающими полями email'):\n            username1, password1, email1 = create_fake_user\n            username2 = username1[:6] + 'q'\n        with allure.step('Получаем объект страницы регистрации'):\n            reg_page = self.login_page.sign_up(reg_page_object)\n        with allure.step('Проверяем корректное отображение ошибки на странице регистрации'):\n            try:\n                reg_page.sign_up(username2, email1, password1, home_page_object)\n            except InvalidRegInfoException as exception:\n                allure.attach(self.driver.get_screenshot_as_png(), 'Error screen', allure.attachment_type.PNG)\n                self.logger.stop_logging()\n                allure.attach(self.logger.get_log_info(), 'App log', allure.attachment_type.TEXT)\n>               raise exception\n\ncreate_fake_user = ('zuevfeofan', '^zSHvb&$Q2', 'ponomarevtaras@rao.com')\nemail1     = 'ponomarevtaras@rao.com'\nhome_page_object = <ui.pages.home_page.HomePage object at 0x7f214258f070>\npassword1  = '^zSHvb&$Q2'\nreg_page   = <ui.pages.reg_page.RegPage object at 0x7f214258fee0>\nreg_page_object = <ui.pages.reg_page.RegPage object at 0x7f214258fee0>\nself       = <test_ui.TestUI object at 0x7f21425f4970>\nusername1  = 'zuevfeofan'\nusername2  = 'zuevfeq'\n\nproject/tests/test_ui.py:531: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nproject/tests/test_ui.py:526: in test_sign_up_negative_17\n    reg_page.sign_up(username2, email1, password1, home_page_object)\n        create_fake_user = ('zuevfeofan', '^zSHvb&$Q2', 'ponomarevtaras@rao.com')\n        email1     = 'ponomarevtaras@rao.com'\n        home_page_object = <ui.pages.home_page.HomePage object at 0x7f214258f070>\n        password1  = '^zSHvb&$Q2'\n        reg_page   = <ui.pages.reg_page.RegPage object at 0x7f214258fee0>\n        reg_page_object = <ui.pages.reg_page.RegPage object at 0x7f214258fee0>\n        self       = <test_ui.TestUI object at 0x7f21425f4970>\n        username1  = 'zuevfeofan'\n        username2  = 'zuevfeq'\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <ui.pages.reg_page.RegPage object at 0x7f214258fee0>\nusername = 'zuevfeq', email = 'ponomarevtaras@rao.com', password = '^zSHvb&$Q2'\nhome_page_object = <ui.pages.home_page.HomePage object at 0x7f214258f070>\nwrong_password = None\n\n    def sign_up(self, username, email, password, home_page_object, wrong_password=None):\n        self.paste_sign_up_info(username, email, password, wrong_password=wrong_password)\n        self.click_accept_reg_button()\n        self.click_submit_button()\n        try:\n            if wait(func=self.check_available_of_element(self.locators.POP_UP_ERR_FIELD, auto_use=False), timeout=1):\n>               raise InvalidRegInfoException(self.find(self.locators.POP_UP_ERR_FIELD).text)\nE               ui.utils.exceptions.InvalidRegInfoException: Internal Server Error\n\nemail      = 'ponomarevtaras@rao.com'\nhome_page_object = <ui.pages.home_page.HomePage object at 0x7f214258f070>\npassword   = '^zSHvb&$Q2'\nself       = <ui.pages.reg_page.RegPage object at 0x7f214258fee0>\nusername   = 'zuevfeq'\nwrong_password = None\n\nproject/ui/pages/reg_page.py:31: InvalidRegInfoException"}, "description": "Проверка регистрации пользователя при совпадении поля email с уже существующим в БД", "steps": [{"name": "Получаем информацию о пользователях с совпадающими полями email", "status": "passed", "start": 1590595705902, "stop": 1590595705902}, {"name": "Получаем объект страницы регистрации", "status": "passed", "start": 1590595705902, "stop": 1590595706022}, {"name": "Проверяем корректное отображение ошибки на странице регистрации", "status": "broken", "statusDetails": {"message": "ui.utils.exceptions.InvalidRegInfoException: Internal Server Error\n", "trace": "  File \"/media/qunity/Workspace/Python_projects/qa-project/project/tests/test_ui.py\", line 531, in test_sign_up_negative_17\n    raise exception\n  File \"/media/qunity/Workspace/Python_projects/qa-project/project/tests/test_ui.py\", line 526, in test_sign_up_negative_17\n    reg_page.sign_up(username2, email1, password1, home_page_object)\n  File \"/media/qunity/Workspace/Python_projects/qa-project/project/ui/pages/reg_page.py\", line 31, in sign_up\n    raise InvalidRegInfoException(self.find(self.locators.POP_UP_ERR_FIELD).text)\n"}, "attachments": [{"name": "Error screen", "source": "6719304f-8d41-4734-8d03-234c4c0a339d-attachment.png", "type": "image/png"}, {"name": "App log", "source": "7a3a7f94-25c9-4691-acdc-11a923f29fe9-attachment.txt", "type": "text/plain"}], "start": 1590595706022, "stop": 1590595707746}], "start": 1590595705834, "stop": 1590595707746, "uuid": "b2a1c248-c225-4ee3-ab20-b9c27ae70532", "historyId": "3718d4b448e6a86acc280012a017c1ff", "testCaseId": "c439d4f64cf109196129d363c71bca4b", "fullName": "tests.test_ui.TestUI#test_sign_up_negative_17", "labels": [{"name": "feature", "value": "UI tests"}, {"name": "story", "value": "Sign up page story"}, {"name": "tag", "value": "UI"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_ui"}, {"name": "subSuite", "value": "TestUI"}, {"name": "host", "value": "dmaksimov-laptop"}, {"name": "thread", "value": "22077-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_ui"}]}