{"name": "test_add_user_6[0]", "status": "broken", "statusDetails": {"message": "api.utils.exceptions.ResponseStatusCodeException:  Got 210 UNKNOWN for URL \"http://172.18.0.5:8080/api/add_user\"", "trace": "self = <test_api.TestApi object at 0x7fee390f37c0>\nget_fake_user_info = ('vladimir1991', 'V$PpG3Dm)j', 'stanislav_1970@ip.net')\npart_of_email = 0\n\n    @allure.feature('API tests')\n    @allure.story('Add user api story')\n    @pytest.mark.parametrize('part_of_email', [0, 1])\n    def test_add_user_6(self, get_fake_user_info, part_of_email):\n        \"\"\"Проверка создания пользователя с невалидным полем email\"\"\"\n        self.logger.start_logging(f'./project/app_logs/{inspect.getframeinfo(inspect.currentframe()).function}_api_log_{part_of_email}.txt')\n        with allure.step('Создаём фейковые данные пользователя'):\n            username, password, email = get_fake_user_info\n            if len(username) > 17:\n                username = username[:10]\n            if part_of_email == 1:\n                email = '@' + email.split('@')[part_of_email]\n            else:\n                email = email.split('@')[part_of_email]\n        with allure.step('Входим на сайт'):\n            self.api_client.login()\n        with allure.step('Добавляем данные о пользователе'):\n            try:\n                response = self.api_client.add_user(username, password, email, autoremove=True, status_code=400)\n            except ResponseStatusCodeException as exception:\n                self.api_client.logout()\n                self.logger.stop_logging()\n                allure.attach(self.logger.get_log_info(), 'App log', allure.attachment_type.TEXT)\n>               raise exception\n\nemail      = 'stanislav_1970'\nget_fake_user_info = ('vladimir1991', 'V$PpG3Dm)j', 'stanislav_1970@ip.net')\npart_of_email = 0\npassword   = 'V$PpG3Dm)j'\nself       = <test_api.TestApi object at 0x7fee390f37c0>\nusername   = 'vladimir1991'\n\nproject/tests/test_api.py:244: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nproject/tests/test_api.py:239: in test_add_user_6\n    response = self.api_client.add_user(username, password, email, autoremove=True, status_code=400)\n        email      = 'stanislav_1970'\n        get_fake_user_info = ('vladimir1991', 'V$PpG3Dm)j', 'stanislav_1970@ip.net')\n        part_of_email = 0\n        password   = 'V$PpG3Dm)j'\n        self       = <test_api.TestApi object at 0x7fee390f37c0>\n        username   = 'vladimir1991'\nproject/api/client.py:93: in add_user\n    raise exception\n        autoremove = True\n        data       = {'email': 'stanislav_1970', 'password': 'V$PpG3Dm)j', 'username': 'vladimir1991'}\n        email      = 'stanislav_1970'\n        headers    = {'Content-Type': 'application/json'}\n        location   = 'api/add_user'\n        password   = 'V$PpG3Dm)j'\n        self       = <api.client.ApiClient object at 0x7fee38f460d0>\n        status_code = 400\n        username   = 'vladimir1991'\nproject/api/client.py:89: in add_user\n    response = self.make_request('POST', location, json_convert=False, headers=headers, allow_redirects=False, json=data, status_code=201 if status_code is None else status_code)\n        autoremove = True\n        data       = {'email': 'stanislav_1970', 'password': 'V$PpG3Dm)j', 'username': 'vladimir1991'}\n        email      = 'stanislav_1970'\n        headers    = {'Content-Type': 'application/json'}\n        location   = 'api/add_user'\n        password   = 'V$PpG3Dm)j'\n        self       = <api.client.ApiClient object at 0x7fee38f460d0>\n        status_code = 400\n        username   = 'vladimir1991'\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <api.client.ApiClient object at 0x7fee38f460d0>, method = 'POST'\nlocation = 'api/add_user', status_code = 400\nheaders = {'Content-Type': 'application/json'}, params = None, data = None\njson_convert = False, custom_location = False, allow_redirects = False\njson = {'email': 'stanislav_1970', 'password': 'V$PpG3Dm)j', 'username': 'vladimir1991'}\n\n    def make_request(self, method, location, status_code=200, headers=None, params=None, data=None, json_convert=True,\n                     custom_location=False, allow_redirects=True, json=None):\n        if not custom_location:\n            url = urljoin(self.base_url, location)\n        else:\n            url = location\n    \n        response = self.session.request(method, url, headers=headers, params=params, data=data,\n                                        allow_redirects=allow_redirects, json=json)\n    \n        if response.status_code != status_code:\n>           raise ResponseStatusCodeException(f' Got {response.status_code} {response.reason} for URL \"{url}\"')\nE           api.utils.exceptions.ResponseStatusCodeException:  Got 210 UNKNOWN for URL \"http://172.18.0.5:8080/api/add_user\"\n\nallow_redirects = False\ncustom_location = False\ndata       = None\nheaders    = {'Content-Type': 'application/json'}\njson       = {'email': 'stanislav_1970', 'password': 'V$PpG3Dm)j', 'username': 'vladimir1991'}\njson_convert = False\nlocation   = 'api/add_user'\nmethod     = 'POST'\nparams     = None\nresponse   = <Response [210]>\nself       = <api.client.ApiClient object at 0x7fee38f460d0>\nstatus_code = 400\nurl        = 'http://172.18.0.5:8080/api/add_user'\n\nproject/api/client.py:28: ResponseStatusCodeException"}, "description": "Проверка создания пользователя с невалидным полем email", "steps": [{"name": "Создаём фейковые данные пользователя", "status": "passed", "start": 1590595239379, "stop": 1590595239379}, {"name": "Входим на сайт", "status": "passed", "start": 1590595239379, "stop": 1590595239418}, {"name": "Добавляем данные о пользователе", "status": "broken", "statusDetails": {"message": "api.utils.exceptions.ResponseStatusCodeException:  Got 210 UNKNOWN for URL \"http://172.18.0.5:8080/api/add_user\"\n", "trace": "  File \"/media/qunity/Workspace/Python_projects/qa-project/project/tests/test_api.py\", line 244, in test_add_user_6\n    raise exception\n  File \"/media/qunity/Workspace/Python_projects/qa-project/project/tests/test_api.py\", line 239, in test_add_user_6\n    response = self.api_client.add_user(username, password, email, autoremove=True, status_code=400)\n  File \"/media/qunity/Workspace/Python_projects/qa-project/project/api/client.py\", line 93, in add_user\n    raise exception\n  File \"/media/qunity/Workspace/Python_projects/qa-project/project/api/client.py\", line 89, in add_user\n    response = self.make_request('POST', location, json_convert=False, headers=headers, allow_redirects=False, json=data, status_code=201 if status_code is None else status_code)\n  File \"/media/qunity/Workspace/Python_projects/qa-project/project/api/client.py\", line 28, in make_request\n    raise ResponseStatusCodeException(f' Got {response.status_code} {response.reason} for URL \"{url}\"')\n"}, "attachments": [{"name": "App log", "source": "d2eacbe9-f6c0-4600-bddf-80afbfdc4d1d-attachment.txt", "type": "text/plain"}], "start": 1590595239418, "stop": 1590595239632}], "parameters": [{"name": "part_of_email", "value": "0"}], "start": 1590595239309, "stop": 1590595239632, "uuid": "434d29ac-d3f8-47a8-8812-a13e1ae2405d", "historyId": "cd36123f33ebbd88cdf04259f198f907", "testCaseId": "1497c19ad407964e42891073176567ab", "fullName": "tests.test_api.TestApi#test_add_user_6", "labels": [{"name": "feature", "value": "API tests"}, {"name": "story", "value": "Add user api story"}, {"name": "tag", "value": "API"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "dmaksimov-laptop"}, {"name": "thread", "value": "18998-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}