{"name": "test_add_user_1", "status": "broken", "statusDetails": {"message": "api.utils.exceptions.ResponseStatusCodeException:  Got 210 UNKNOWN for URL \"http://172.18.0.5:8080/api/add_user\"", "trace": "self = <test_api.TestApi object at 0x7fc356d73ca0>\nget_fake_user_info = ('leonideliseev', '%_%ZnHIud9', 'darja_2010@rambler.ru')\n\n    @allure.feature('API tests')\n    @allure.story('Add user api story')\n    def test_add_user_1(self, get_fake_user_info):\n        \"\"\"Проверка кода ответа при валидном добавлении пользователя\"\"\"\n        self.logger.start_logging(f'./project/app_logs/{inspect.getframeinfo(inspect.currentframe()).function}_api_log.txt')\n        with allure.step('Входим на сайт'):\n            self.api_client.login()\n        with allure.step('Получаем информацию о фейковом пользователе'):\n            username, password, email = get_fake_user_info\n        with allure.step('Добавляем нового пользователя'):\n            try:\n                response = self.api_client.add_user(username, password, email, autoremove=True)\n            except ResponseStatusCodeException as exception:\n                self.api_client.logout()\n                self.logger.stop_logging()\n                allure.attach(self.logger.get_log_info(), 'App log', allure.attachment_type.TEXT)\n>               raise exception\n\nemail      = 'darja_2010@rambler.ru'\nget_fake_user_info = ('leonideliseev', '%_%ZnHIud9', 'darja_2010@rambler.ru')\npassword   = '%_%ZnHIud9'\nself       = <test_api.TestApi object at 0x7fc356d73ca0>\nusername   = 'leonideliseev'\n\nproject/tests/test_api.py:130: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nproject/tests/test_api.py:125: in test_add_user_1\n    response = self.api_client.add_user(username, password, email, autoremove=True)\n        email      = 'darja_2010@rambler.ru'\n        get_fake_user_info = ('leonideliseev', '%_%ZnHIud9', 'darja_2010@rambler.ru')\n        password   = '%_%ZnHIud9'\n        self       = <test_api.TestApi object at 0x7fc356d73ca0>\n        username   = 'leonideliseev'\nproject/api/client.py:93: in add_user\n    raise exception\n        autoremove = True\n        data       = {'email': 'darja_2010@rambler.ru', 'password': '%_%ZnHIud9', 'username': 'leonideliseev'}\n        email      = 'darja_2010@rambler.ru'\n        headers    = {'Content-Type': 'application/json'}\n        location   = 'api/add_user'\n        password   = '%_%ZnHIud9'\n        self       = <api.client.ApiClient object at 0x7fc356cc8d30>\n        status_code = None\n        username   = 'leonideliseev'\nproject/api/client.py:89: in add_user\n    response = self.make_request('POST', location, json_convert=False, headers=headers, allow_redirects=False, json=data, status_code=201 if status_code is None else status_code)\n        autoremove = True\n        data       = {'email': 'darja_2010@rambler.ru', 'password': '%_%ZnHIud9', 'username': 'leonideliseev'}\n        email      = 'darja_2010@rambler.ru'\n        headers    = {'Content-Type': 'application/json'}\n        location   = 'api/add_user'\n        password   = '%_%ZnHIud9'\n        self       = <api.client.ApiClient object at 0x7fc356cc8d30>\n        status_code = None\n        username   = 'leonideliseev'\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <api.client.ApiClient object at 0x7fc356cc8d30>, method = 'POST'\nlocation = 'api/add_user', status_code = 201\nheaders = {'Content-Type': 'application/json'}, params = None, data = None\njson_convert = False, custom_location = False, allow_redirects = False\njson = {'email': 'darja_2010@rambler.ru', 'password': '%_%ZnHIud9', 'username': 'leonideliseev'}\n\n    def make_request(self, method, location, status_code=200, headers=None, params=None, data=None, json_convert=True,\n                     custom_location=False, allow_redirects=True, json=None):\n        if not custom_location:\n            url = urljoin(self.base_url, location)\n        else:\n            url = location\n    \n        response = self.session.request(method, url, headers=headers, params=params, data=data,\n                                        allow_redirects=allow_redirects, json=json)\n    \n        if response.status_code != status_code:\n>           raise ResponseStatusCodeException(f' Got {response.status_code} {response.reason} for URL \"{url}\"')\nE           api.utils.exceptions.ResponseStatusCodeException:  Got 210 UNKNOWN for URL \"http://172.18.0.5:8080/api/add_user\"\n\nallow_redirects = False\ncustom_location = False\ndata       = None\nheaders    = {'Content-Type': 'application/json'}\njson       = {'email': 'darja_2010@rambler.ru', 'password': '%_%ZnHIud9', 'username': 'leonideliseev'}\njson_convert = False\nlocation   = 'api/add_user'\nmethod     = 'POST'\nparams     = None\nresponse   = <Response [210]>\nself       = <api.client.ApiClient object at 0x7fc356cc8d30>\nstatus_code = 201\nurl        = 'http://172.18.0.5:8080/api/add_user'\n\nproject/api/client.py:28: ResponseStatusCodeException"}, "description": "Проверка кода ответа при валидном добавлении пользователя", "steps": [{"name": "Входим на сайт", "status": "passed", "start": 1590595238862, "stop": 1590595238889}, {"name": "Получаем информацию о фейковом пользователе", "status": "passed", "start": 1590595238889, "stop": 1590595238889}, {"name": "Добавляем нового пользователя", "status": "broken", "statusDetails": {"message": "api.utils.exceptions.ResponseStatusCodeException:  Got 210 UNKNOWN for URL \"http://172.18.0.5:8080/api/add_user\"\n", "trace": "  File \"/media/qunity/Workspace/Python_projects/qa-project/project/tests/test_api.py\", line 130, in test_add_user_1\n    raise exception\n  File \"/media/qunity/Workspace/Python_projects/qa-project/project/tests/test_api.py\", line 125, in test_add_user_1\n    response = self.api_client.add_user(username, password, email, autoremove=True)\n  File \"/media/qunity/Workspace/Python_projects/qa-project/project/api/client.py\", line 93, in add_user\n    raise exception\n  File \"/media/qunity/Workspace/Python_projects/qa-project/project/api/client.py\", line 89, in add_user\n    response = self.make_request('POST', location, json_convert=False, headers=headers, allow_redirects=False, json=data, status_code=201 if status_code is None else status_code)\n  File \"/media/qunity/Workspace/Python_projects/qa-project/project/api/client.py\", line 28, in make_request\n    raise ResponseStatusCodeException(f' Got {response.status_code} {response.reason} for URL \"{url}\"')\n"}, "attachments": [{"name": "App log", "source": "054ae9b2-dcff-4bdd-bc9e-d566ca0891da-attachment.txt", "type": "text/plain"}], "start": 1590595238889, "stop": 1590595239130}], "start": 1590595238653, "stop": 1590595239130, "uuid": "46d2ea69-4d8e-4bc6-b646-268eab43803d", "historyId": "4e7bff2dfa54df436e73a3ae0324adfa", "testCaseId": "4b0dc9010bd764d2c49b21b57f6d72be", "fullName": "tests.test_api.TestApi#test_add_user_1", "labels": [{"name": "story", "value": "Add user api story"}, {"name": "feature", "value": "API tests"}, {"name": "tag", "value": "API"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "dmaksimov-laptop"}, {"name": "thread", "value": "19002-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}