{"name": "test_add_user_3[6]", "status": "broken", "statusDetails": {"message": "api.utils.exceptions.ResponseStatusCodeException:  Got 210 UNKNOWN for URL \"http://172.18.0.5:8080/api/add_user\"", "trace": "self = <test_api.TestApi object at 0x7f206e3157f0>, len_username = 6\nget_fake_user_info = ('hustinov', '#Zm51WYd)d', 'kondrat_10@ooo.biz')\n\n    @allure.feature('API tests')\n    @allure.story('Add user api story')\n    @pytest.mark.parametrize('len_username', [1, 2, 3, 4, 5, 6, 20])\n    def test_add_user_3(self, len_username, get_fake_user_info):\n        \"\"\"Проверка валидации длины поля username\"\"\"\n        self.logger.start_logging(f'./project/app_logs/{inspect.getframeinfo(inspect.currentframe()).function}_api_log_{len_username}.txt')\n        with allure.step('Входим на сайт'):\n            self.api_client.login()\n        with allure.step('Создаём фейковые данные пользователя'):\n            username, password, email = get_fake_user_info\n            if len(username) < len_username:\n                username *= 5\n                username = username[:len_username]\n            else:\n                username = username[:len_username]\n        with allure.step('Добавляем данные о пользователе'):\n            try:\n                response = self.api_client.add_user(username, password, email, autoremove=True)\n            except ResponseStatusCodeException as exception:\n                self.api_client.logout()\n                self.logger.stop_logging()\n                allure.attach(self.logger.get_log_info(), 'App log', allure.attachment_type.TEXT)\n>               raise exception\n\nemail      = 'kondrat_10@ooo.biz'\nget_fake_user_info = ('hustinov', '#Zm51WYd)d', 'kondrat_10@ooo.biz')\nlen_username = 6\npassword   = '#Zm51WYd)d'\nself       = <test_api.TestApi object at 0x7f206e3157f0>\nusername   = 'hustin'\n\nproject/tests/test_api.py:173: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nproject/tests/test_api.py:168: in test_add_user_3\n    response = self.api_client.add_user(username, password, email, autoremove=True)\n        email      = 'kondrat_10@ooo.biz'\n        get_fake_user_info = ('hustinov', '#Zm51WYd)d', 'kondrat_10@ooo.biz')\n        len_username = 6\n        password   = '#Zm51WYd)d'\n        self       = <test_api.TestApi object at 0x7f206e3157f0>\n        username   = 'hustin'\nproject/api/client.py:93: in add_user\n    raise exception\n        autoremove = True\n        data       = {'email': 'kondrat_10@ooo.biz', 'password': '#Zm51WYd)d', 'username': 'hustin'}\n        email      = 'kondrat_10@ooo.biz'\n        headers    = {'Content-Type': 'application/json'}\n        location   = 'api/add_user'\n        password   = '#Zm51WYd)d'\n        self       = <api.client.ApiClient object at 0x7f206e315b20>\n        status_code = None\n        username   = 'hustin'\nproject/api/client.py:89: in add_user\n    response = self.make_request('POST', location, json_convert=False, headers=headers, allow_redirects=False, json=data, status_code=201 if status_code is None else status_code)\n        autoremove = True\n        data       = {'email': 'kondrat_10@ooo.biz', 'password': '#Zm51WYd)d', 'username': 'hustin'}\n        email      = 'kondrat_10@ooo.biz'\n        headers    = {'Content-Type': 'application/json'}\n        location   = 'api/add_user'\n        password   = '#Zm51WYd)d'\n        self       = <api.client.ApiClient object at 0x7f206e315b20>\n        status_code = None\n        username   = 'hustin'\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <api.client.ApiClient object at 0x7f206e315b20>, method = 'POST'\nlocation = 'api/add_user', status_code = 201\nheaders = {'Content-Type': 'application/json'}, params = None, data = None\njson_convert = False, custom_location = False, allow_redirects = False\njson = {'email': 'kondrat_10@ooo.biz', 'password': '#Zm51WYd)d', 'username': 'hustin'}\n\n    def make_request(self, method, location, status_code=200, headers=None, params=None, data=None, json_convert=True,\n                     custom_location=False, allow_redirects=True, json=None):\n        if not custom_location:\n            url = urljoin(self.base_url, location)\n        else:\n            url = location\n    \n        response = self.session.request(method, url, headers=headers, params=params, data=data,\n                                        allow_redirects=allow_redirects, json=json)\n    \n        if response.status_code != status_code:\n>           raise ResponseStatusCodeException(f' Got {response.status_code} {response.reason} for URL \"{url}\"')\nE           api.utils.exceptions.ResponseStatusCodeException:  Got 210 UNKNOWN for URL \"http://172.18.0.5:8080/api/add_user\"\n\nallow_redirects = False\ncustom_location = False\ndata       = None\nheaders    = {'Content-Type': 'application/json'}\njson       = {'email': 'kondrat_10@ooo.biz', 'password': '#Zm51WYd)d', 'username': 'hustin'}\njson_convert = False\nlocation   = 'api/add_user'\nmethod     = 'POST'\nparams     = None\nresponse   = <Response [210]>\nself       = <api.client.ApiClient object at 0x7f206e315b20>\nstatus_code = 201\nurl        = 'http://172.18.0.5:8080/api/add_user'\n\nproject/api/client.py:28: ResponseStatusCodeException"}, "description": "Проверка валидации длины поля username", "steps": [{"name": "Входим на сайт", "status": "passed", "start": 1590595239214, "stop": 1590595239243}, {"name": "Создаём фейковые данные пользователя", "status": "passed", "start": 1590595239243, "stop": 1590595239243}, {"name": "Добавляем данные о пользователе", "status": "broken", "statusDetails": {"message": "api.utils.exceptions.ResponseStatusCodeException:  Got 210 UNKNOWN for URL \"http://172.18.0.5:8080/api/add_user\"\n", "trace": "  File \"/media/qunity/Workspace/Python_projects/qa-project/project/tests/test_api.py\", line 173, in test_add_user_3\n    raise exception\n  File \"/media/qunity/Workspace/Python_projects/qa-project/project/tests/test_api.py\", line 168, in test_add_user_3\n    response = self.api_client.add_user(username, password, email, autoremove=True)\n  File \"/media/qunity/Workspace/Python_projects/qa-project/project/api/client.py\", line 93, in add_user\n    raise exception\n  File \"/media/qunity/Workspace/Python_projects/qa-project/project/api/client.py\", line 89, in add_user\n    response = self.make_request('POST', location, json_convert=False, headers=headers, allow_redirects=False, json=data, status_code=201 if status_code is None else status_code)\n  File \"/media/qunity/Workspace/Python_projects/qa-project/project/api/client.py\", line 28, in make_request\n    raise ResponseStatusCodeException(f' Got {response.status_code} {response.reason} for URL \"{url}\"')\n"}, "attachments": [{"name": "App log", "source": "3b7d2a63-219b-4ae6-aa9d-222807946bf9-attachment.txt", "type": "text/plain"}], "start": 1590595239243, "stop": 1590595239531}], "parameters": [{"name": "len_username", "value": "6"}], "start": 1590595239092, "stop": 1590595239531, "uuid": "31b8e0f6-a20f-4432-bc2d-5fefe0a5d9cd", "historyId": "cb934a19a0175fd3ddfbfad25d502faf", "testCaseId": "07f92a0228109d27fe9a842cbc283dd8", "fullName": "tests.test_api.TestApi#test_add_user_3", "labels": [{"name": "feature", "value": "API tests"}, {"name": "story", "value": "Add user api story"}, {"name": "tag", "value": "API"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "dmaksimov-laptop"}, {"name": "thread", "value": "18989-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}